Repository NateRolo/comp2522_lab2, pull requests merged in 2025-01, with the labels that each got.

#2 Elf class updates
  src/code/ca/bcit/comp2522/creature/Creature.java
  src/code/ca/bcit/comp2522/creature/Elf.java
Labels: enhancement

#5 Orc class updates nate
  src/code/ca/bcit/comp2522/creature/LowRageException.java
  src/code/ca/bcit/comp2522/creature/Orc.java
Labels: documentation, good first issue

#3 Elf class completion
  src/code/ca/bcit/comp2522/creature/Creature.java
  src/code/ca/bcit/comp2522/creature/Date.java
  src/code/ca/bcit/comp2522/creature/Elf.java
  src/code/ca/bcit/comp2522/creature/LowManaException.java
Labels: documentation

#7 added javadocs
  src/code/ca/bcit/comp2522/creature/Dragon.java
Labels: documentation

#8 Creature test updates
  src/tests/CreatureTest.java
Labels: documentation, good first issue

#9 Final jobs done on Dragon class
  src/code/ca/bcit/comp2522/creature/Dragon.java
Labels: enhancement
